import Meme from "../../../components/AiAgents/Meme";
import React from "react";
import {
  generateWebApplicationSchema,
  generateImageObjectSchema,
  generateBreadcrumbList,
} from "../../../components/lib/schemaCode";

const TITLE = "Meme Gen – AI Meme Creator & Trend Generator";
const DESCRIPTION =
  "Create memes instantly with AI-powered humor, trending formats, and auto-caption generation.";
const PAGE_PATH = "ai-agents/meme/";
const SITE_BASE = "https://www.brilworks.com/";
const PAGE_URL = `${process.env.NEXT_PUBLIC_BASE_URL}${PAGE_PATH}`;
const ABSOLUTE_URL = `${SITE_BASE}${PAGE_PATH}`;
const OG_IMAGE = `${process.env.NEXT_PUBLIC_BASE_URL}images/og-ai-agent-development.webp`;
const OG_IMAGE_ABSOLUTE = `${SITE_BASE}images/og-ai-agent-development.webp`;

export const metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: PAGE_URL,
    siteName:
      "AWS Consulting Partner | Gen AI | Product Engineering | Brilworks",
    images: [
      {
        url: OG_IMAGE,
        width: 1200,
        height: 630,
        alt: "Brilworks AI Meme Generator — viral, AI-powered meme tool",
      },
    ],
    locale: "en-US",
    type: "website",
  },
  twitter: {
    title: TITLE,
    description: DESCRIPTION,
    card: "summary_large_image",
    site: "@_Brilworks",
    images: [OG_IMAGE],
  },
  alternates: {
    canonical: PAGE_URL,
  },
};

const page = () => {
  const webApplicationJsonLd = generateWebApplicationSchema({
    name: "Brilworks AI Meme Generator",
    description: DESCRIPTION,
    url: ABSOLUTE_URL,
    applicationCategory: "MultimediaApplication",
    imageUrl: OG_IMAGE_ABSOLUTE,
  });

  const imageObjectJsonLd = generateImageObjectSchema({
    contentUrl: OG_IMAGE_ABSOLUTE,
    caption:
      "Sample meme generated by the Brilworks AI Meme Generator (gemini-2.5-flash-image).",
    width: 1200,
    height: 630,
  });

  const breadcrumbJsonLd = generateBreadcrumbList([
    { name: "Home", url: SITE_BASE },
    { name: "AI Agents", url: `${SITE_BASE}ai-agents/` },
    { name: "Meme Gen", url: ABSOLUTE_URL },
  ]);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: webApplicationJsonLd }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: imageObjectJsonLd }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: breadcrumbJsonLd }}
      />
      <Meme />
    </>
  );
};

export default page;
