import { useState } from "react";
import {
  AlertTriangle,
  CheckCircle,
  XCircle,
  FileText,
  Download,
  ExternalLink,
  Sparkles,
} from "lucide-react";

export default function DocumentComplianceDashboard({
  analysisResult,
  fileName,
  setIsActive,
}) {
  //  < "summary") | "clauses" | ("risks" >
  const [activeTab, setActiveTab] = useState("summary");
  const [selectedRisk, setSelectedRisk] = useState(null);

  const handleExportReport = () => {
    if (!analysisResult) return;

    const reportContent = `
CONTRACT ANALYSIS REPORT
========================

Document: ${fileName}
Analysis Date: ${new Date().toLocaleDateString()}
Compliance Score: ${analysisResult.complianceScore}%

EXECUTIVE SUMMARY
-----------------
${analysisResult.summary}

KEY POINTS
----------
${analysisResult.keyPoints
  .map((point, index) => `${index + 1}. ${point}`)
  .join("\n")}

RISK ALERTS
-----------
${analysisResult.riskItems
  .map(
    (risk) => `
${risk.type.toUpperCase()} RISK: ${risk.title}
Description: ${risk.description}
Clause: "${risk.clause}"
Recommendation: ${risk.recommendation}
`
  )
  .join("\n")}

CLAUSE BREAKDOWN
----------------
${analysisResult.clauseBreakdown
  .map(
    (clause) => `
${clause.category}: ${clause.status.toUpperCase()}
${clause.details}
${clause.recommendation ? `Recommendation: ${clause.recommendation}` : ""}
`
  )
  .join("\n")}

Generated by ContractAI Compliance Checker
    `;

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `contract-analysis-${fileName.replace(
      /\.[^/.]+$/,
      ""
    )}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!analysisResult) return;

    const shareData = {
      title: `Contract Analysis Report - ${fileName}`,
      text: `Contract compliance analysis shows ${
        analysisResult.complianceScore
      }% compliance score with ${
        analysisResult.riskItems.filter((r) => r.type === "high").length
      } high-risk items identified.`,
      url: window.location.href,
    };

    if (
      navigator.share &&
      navigator.canShare &&
      navigator.canShare(shareData)
    ) {
      try {
        await navigator.share(shareData);
      } catch (error) {
        console.log("Error sharing:", error);
        fallbackShare();
      }
    } else {
      fallbackShare();
    }
  };

  const fallbackShare = () => {
    const shareText = `Contract Analysis Report - ${fileName}\n\nCompliance Score: ${
      analysisResult?.complianceScore
    }%\nHigh Risk Items: ${
      analysisResult?.riskItems.filter((r) => r.type === "high").length
    }\n\nGenerated by ContractAI Compliance Checker`;

    if (navigator.clipboard) {
      navigator.clipboard
        .writeText(shareText)
        .then(() => {
          alert("Report summary copied to clipboard!");
        })
        .catch(() => {
          prompt("Copy this report summary:", shareText);
        });
    } else {
      prompt("Copy this report summary:", shareText);
    }
  };

  if (!analysisResult) {
    return (
      <div className="max-w-4xl mx-auto text-center py-12">
        <FileText className="h-16 w-16 text-gray-400 mx-auto mb-4" />
        <h2 className="text-2xl font-bold text-gray-900 mb-2">
          No Document Analyzed Yet
        </h2>
        <p className="text-gray-600">
          Upload a contract to see detailed analysis and compliance results
          here.
        </p>
      </div>
    );
  }

  const getRiskColor = (type) => {
    switch (type) {
      case "high":
        return "text-red-600 bg-red-50 border-red-200";
      case "medium":
        return "text-yellow-600 bg-yellow-50 border-yellow-200";
      case "low":
        return "text-green-600 bg-green-50 border-green-200";
      default:
        return "text-gray-600 bg-gray-50 border-gray-200";
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case "compliant":
        return <CheckCircle className="h-5 w-5 text-green-600" />;
      case "warning":
        return <AlertTriangle className="h-5 w-5 text-yellow-600" />;
      case "risk":
        return <XCircle className="h-5 w-5 text-red-600" />;
      default:
        return <CheckCircle className="h-5 w-5 text-gray-600" />;
    }
  };

  const highRiskCount = analysisResult.riskItems.filter(
    (item) => item.type === "high"
  ).length;
  const mediumRiskCount = analysisResult.riskItems.filter(
    (item) => item.type === "medium"
  ).length;

  return (
    <div className="max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">
              Contract Analysis Results
            </h2>
            <p className="text-gray-600">Document: {fileName}</p>
          </div>
          <div className="flex items-center space-x-3 mt-4 md:mt-0">
            <button
              onClick={() => setIsActive("upload")}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-100 transition-colors"
            >
              <Sparkles className="h-4 w-4" />
              <span>Try New</span>
            </button>
            <button
              onClick={handleExportReport}
              className="flex items-center space-x-2 px-4 py-2 bg-themeColor text-white rounded-lg hover:bg-themeColor/90 transition-colors"
            >
              <Download className="h-4 w-4" />
              <span>Export Report</span>
            </button>
            <button
              onClick={handleShare}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-100 transition-colors"
            >
              <ExternalLink className="h-4 w-4" />
              <span>Share</span>
            </button>
          </div>
        </div>

        {/* Compliance Score */}
        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-medium text-gray-900">
              Compliance Score
            </h3>
            <div className="flex items-center space-x-4">
              <span className="text-sm text-red-600">
                {highRiskCount} High Risk
              </span>
              <span className="text-sm text-yellow-600">
                {mediumRiskCount} Medium Risk
              </span>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <div className="flex-1 bg-gray-200 rounded-full h-3">
              <div
                className={`h-3 rounded-full ${
                  analysisResult.complianceScore >= 80
                    ? "bg-green-500"
                    : analysisResult.complianceScore >= 60
                    ? "bg-yellow-500"
                    : "bg-red-500"
                }`}
                style={{ width: `${analysisResult.complianceScore}%` }}
              ></div>
            </div>
            <span className="text-2xl font-bold text-gray-900">
              {analysisResult.complianceScore}%
            </span>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200 mb-6">
        <nav className="flex space-x-8">
          {[
            { id: "summary", label: "Summary", count: null },
            {
              id: "clauses",
              label: "Clause Breakdown",
              count: analysisResult.clauseBreakdown.length,
            },
            {
              id: "risks",
              label: "Risk Alerts",
              count: analysisResult.riskItems.length,
            },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab?.id)}
              className={`py-2 px-1 border-b-2 font-medium text-sm transition-colors ${
                activeTab === tab.id
                  ? "border-blue-500 text-blue-600"
                  : "border-transparent text-gray-500 hover:text-gray-700"
              }`}
            >
              {tab.label}
              {tab.count !== null && (
                <span className="ml-2 px-2 py-1 text-xs bg-gray-100 rounded-full">
                  {tab.count}
                </span>
              )}
            </button>
          ))}
        </nav>
      </div>

      {/* Tab Content */}
      {activeTab === "summary" && (
        <div className="space-y-6">
          <div className="bg-white rounded-lg border border-gray-200 p-6">
            <h3 className="text-xl font-medium text-gray-900 mb-4">
              Plain Language Summary
            </h3>
            <p className="text-gray-700 leading-relaxed">
              {analysisResult.summary}
            </p>
          </div>

          <div className="bg-white rounded-lg border border-gray-200 p-6">
            <h3 className="text-xl font-medium text-gray-900 mb-4">
              Key Points
            </h3>
            <ul className="space-y-2">
              {analysisResult.keyPoints.map((point, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <CheckCircle className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {activeTab === "clauses" && (
        <div className="space-y-4">
          {analysisResult.clauseBreakdown.map((clause, index) => (
            <div
              key={index}
              className="bg-white rounded-lg border border-gray-200 p-6"
            >
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-lg font-medium text-gray-900">
                  {clause.category}
                </h3>
                {getStatusIcon(clause.status)}
              </div>
              <p className="text-gray-700 mb-3">{clause.details}</p>
              {clause.recommendation && (
                <div className="bg-blue-50 rounded-lg p-3">
                  <p className="text-sm text-blue-800">
                    <strong>Recommendation:</strong> {clause.recommendation}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {activeTab === "risks" && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            {analysisResult.riskItems.map((risk) => (
              <div
                key={risk.id}
                className={`border rounded-lg p-4 cursor-pointer transition-colors ${
                  selectedRisk?.id === risk.id
                    ? "ring-2 ring-blue-500 bg-blue-50"
                    : "hover:bg-gray-50"
                } ${getRiskColor(risk.type)}`}
                onClick={() => setSelectedRisk(risk)}
              >
                <div className="flex items-start justify-between mb-2">
                  <h4 className="font-medium">{risk.title}</h4>
                  <span className="text-xs px-2 py-1 rounded-full bg-white border">
                    {risk.type.toUpperCase()}
                  </span>
                </div>
                <p className="text-sm opacity-80">{risk.description}</p>
              </div>
            ))}
          </div>

          <div className="lg:sticky lg:top-24">
            {selectedRisk ? (
              <div className="bg-white rounded-lg border border-gray-200 p-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">
                  Risk Details
                </h3>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-1">Issue</h4>
                    <p className="text-gray-700">{selectedRisk.description}</p>
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 mb-1">
                      Clause Text
                    </h4>
                    <p className="text-sm bg-gray-50 p-3 rounded-lg italic">
                      "{selectedRisk.clause}"
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 mb-1">
                      Recommendation
                    </h4>
                    <p className="text-gray-700">
                      {selectedRisk.recommendation}
                    </p>
                  </div>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-lg border border-gray-200 p-6 text-center">
                <AlertTriangle className="h-12 w-12 text-gray-400 mx-auto mb-3" />
                <p className="text-gray-600">
                  Select a risk item to view details
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
