export const brilworksProducts = [
  {
    title: "Restaurant",
    description: "Smart restaurant management and digital ordering solution.",
    image: "/images/products/restaurant.png",
    link: "https://restaurant.brilworks.com/",
    image: "/images/asset/restaurant-p.webp",
    bg: "bg-blue-200",
  },
  {
    title: "HRTech",
    description: "Modern HR and recruitment management platform.",
    image: "/images/products/hrtech.png",
    link: "https://hrtech.brilworks.com/",
    image: "/images/asset/hr-tech-p.webp",
    bg: "bg-indigo-200",
  },
  {
    title: "Circle Contact",
    description: "Smart contact and communication management system.",
    image: "/images/products/contact.png",
    link: "https://circle.brilworks.com/",
    image: "/images/asset/circle-contact-p.webp",
    bg: "bg-purple-200",
  },
  {
    title: "Life AI",
    description: "AI-powered personal and productivity assistant.",
    image: "/images/products/lifeai.png",
    link: "https://lifeai.brilworks.com/",
    image: "/images/asset/life-ai-p.webp",
    bg: "bg-teal-200",
  },

  {
    title: "RealEstate",
    description: "Real estate listing and property management platform.",
    image: "/images/products/realestate.png",
    link: "https://realestate.brilworks.com/",
    image: "/images/asset/real-estate-p.webp",
    bg: "bg-orange-200",
  },
  {
    title: "VectorTrace",
    description: "Convert raster images into scalable vector graphics.",
    image: "/images/products/vectortrace.png",
    link: "https://vectortrace.brilworks.com/",
    image: "/images/asset/vector-trace-p.webp",
    bg: "bg-rose-200",
  },
  {
    title: "ScanEat",
    description: "Scan-based food ordering and smart dining experience.",
    image: "/images/products/scaneat.png",
    link: "https://scaneat.brilworks.com/",
    image: "/images/asset/scan-eat-p.webp",
    bg: "bg-green-200",
  },
  {
    title: "CourseSphere",
    description: "Online course management and learning platform.",
    image: "/images/products/courses.png",
    link: "https://coursesphere.brilworks.com/",
    image: "/images/asset/course-sphere-p.webp",
    bg: "bg-yellow-200",
  },
  {
    title: "Voice",
    description: "Voice-based AI interaction and automation tool.",
    image: "/images/products/voice.png",
    link: "https://voice.brilworks.com/",
    image: "/images/asset/voice-p.webp",
    bg: "bg-pink-200",
  },
  {
    title: "GarageMap",
    description: "Smart parking and garage management solution.",
    image: "/images/products/garagemap.png",
    link: "https://garagemap.brilworks.com/",
    image: "/images/asset/garage-map-p.webp",
    bg: "bg-lime-200",
  },
];
